server:
  port: 8081

logging:
  file:
    path: '/home/jhpark/codari/gathering-webapp/log/'
  pattern:
    file: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

spring:
  application:
    name: codari-gathering
  profiles:
    include: file-logging
  config:
    use-legacy-processing: true
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/codari-gathering?useSSL=false
    username: codari-gathering
    password: codari
  flyway:
    enabled: true
    baseline-on-migrate: true
    user: codari-gathering
    password: codari
    url: 'jdbc:mysql://localhost:3306/codari-gathering?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false'


codari:
  url: 'cooodari.com'